# Generated by Django 5.2.17 on 2026-08-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.assetcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی دارایی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای دارایی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام محل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد محل')),
                ('location_type', models.CharField(choices=[('organization', 'سازمان'), ('building', 'ساختمان'), ('floor', 'طبقه'), ('room', 'اتاق'), ('warehouse', 'انبار'), ('office', 'دفتر'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع محل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.location', verbose_name='محل والد')),
            ],
            options={
                'verbose_name': 'محل',
                'verbose_name_plural': 'محل\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='کد اموال')),
                ('name', models.CharField(max_length=255, verbose_name='نام دارایی')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره سریال')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت خرید')),
                ('status', models.CharField(choices=[('active', 'در حال استفاده'), ('available', 'آماده تخصیص'), ('repair', 'در تعمیر'), ('damaged', 'خراب'), ('disposed', 'اسقاط شده'), ('lost', 'مفقود'), ('sold', 'فروخته شده')], default='available', max_length=20, verbose_name='وضعیت')),
                ('warranty_start', models.DateField(blank=True, null=True, verbose_name='شروع گارانتی')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='پایان گارانتی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='دسته\u200cبندی')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.location', verbose_name='محل استقرار')),
            ],
            options={
                'verbose_name': 'دارایی',
                'verbose_name_plural': 'دارایی ها',
                'ordering': ['name'],
            },
        ),
    ]
